
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore_dev -d bookstore_dev_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONPATH: "/app"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres_data: